### ISSUE TITLE
New logo for TickTock-Wear

### ISSUE THREAD

**Issue by elawhatson** [LayoutXML/TickTock-Wear#1]
Well, here we gonna be working on the logo, 😃

**Comment by LayoutXML** [comment]
Hi,
So I don't have anything on my mind about the logo. I've tried multipel variations by combining volume and watch icons but then the icon seems to be too complicated.

App itself doesn't have any unique elements that could be added to the logo, only the big blue circle play button (#03A9F4) whose color could be used.

**Comment by elawhatson** [comment]
What do you think, I made a different watch with sound waves.
![test](https://user-images.githubusercontent.com/43912079/47398310-92a49980-d701-11e8-9496-156aef6b0813.png)

**Comment by LayoutXML** [comment]
Looks cool!

**Comment by elawhatson** [comment]
Do you like the colors?

**Comment by LayoutXML** [comment]
Yeah I do

**Comment by elawhatson** [comment]
great!. I'll make the Pull Request then.😃

**Comment by LayoutXML** [comment]
Hi,
Thank you for your logo. Can you also share the high resolution image?

**Comment by LayoutXML** [comment]
Hi,

I'm ready to release the app. Could you share the 512x512 (web) size image like with the Twelveish?
